// <auto-generated />
using System;
using FuturesClean.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FuturesClean.API.Data.Migrations
{
    [DbContext(typeof(AppDBContext))]
    partial class AppDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FuturesClean.API.Domain.Entities.FuturesDifference", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("pk_futures_difference_id");

                    b.Property<string>("Interval")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("interval");

                    b.Property<string>("Spread")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("spread");

                    b.Property<string>("SymbolCurrent")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("symbol_current");

                    b.Property<string>("SymbolNext")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("symbol_next");

                    b.Property<DateTime>("TimeMeasuredUtc")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("time_measured_utc");

                    b.HasKey("Id");

                    b.ToTable("futures_difference", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
